### ISSUE TITLE
Better error handling for gtm.Trafficmanager.

### ISSUE THREAD

**Issue by Raffo** [zalando-techmonkeys/baboon-proxy#24]
As commented here https://github.com/zalando-techmonkeys/baboon-proxy/pull/23/files#r46685829, we need to implement better error handling when `gtm.Trafficmanager` is used. Right now we're only logging the error which could lead to potential problems. See for reference: https://github.com/zalando-techmonkeys/baboon-proxy/commit/008f8a47fd65af17ecac51a4a39550fd0e3cb7c8.

**Comment by njuettner** [comment]
Should be fixed in PR https://github.com/zalando-techmonkeys/baboon-proxy/pull/32
